program     # program 
 ident      # exemploErro2 
 abre_parenteses      # ( 
 ident      # input 
 virgula      # , 
 ident      # output 
 fecha_parenteses     # ) 
 pt_virgula      # ; 
var      # var 
 ident      # n 
 virgula      # , 
 ident      # k 
 dois pontos     # : 
 ident      # integer 
 pt_virgula      # ; 
begin     # begin 
 simb_read     # read 
 abre_parenteses      # ( 
 ident      # n 
 fecha_parenteses     # ) 
 pt_virgula      # ; 
 simb_read     # read 
 abre_parenteses      # ( 
 ident      # k 
 fecha_parenteses     # ) 
 pt_virgula      # ; 
if      # if 
 abre_parenteses      # ( 
 ident      # n 
 simb_adicao     # + 
 numero      # 1 
 fecha_parenteses     # ) 
 simb_then     # then 
